### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by janalkema** [kbentlage/da-redis-management#1]
Is it possible (or better) to change the directory var/lib/redis to home/redis as sometimes the root diectory is not big enough for large databases.

**Comment by poralix** [comment]
Hello,

Could you try and use symlink from /var/lib/redis to /home/redis. It should work fine.

p.s. I'm not the author of the plugin, but we install it for our clients. And have some experience with it.

**Comment by kbentlage** [comment]
Hi Guys,

Thanks for the request, i think it's a nice improvement.

I will look into this asap, i think i make a configuration somewhere so that you can deside for yourself where you like to have the data directory of redis.

To be continued!

**Comment by janalkema** [comment]
Hi, first thank you for your answer.
#Poralix, I did create a symlink, but for some reason, after that when creating a new Redis instance it duplicates (create two instances). The same with deleting a database, then I got an error).

I could try it again after clean install. How can I be sure that I clean/delete everything first after installing this great plugin?

**Comment by kbentlage** [comment]
I think you need to take the following steps to completely remove the plugin (and redis)

# Cleanup redis
yum remove redis
rm -rf /var/lib/redis
rm -f /etc/redis.conf
rm -rf /etc/redis/

# Remove plugin
rm -rf /usr/local/directadmin/plugins/redis_management/
rm -f /etc/sudoers.d/redis

Then you can reinstall the plugin.

**Comment by janalkema** [comment]
Thanks!! Looking forward to your improvement :)

**Comment by kbentlage** [comment]
I've added configuration functionalities, so you can define which directory redis should use for storing instance data. You can also change stuff like the user and group that redis uses to run.

I've merged these changes in the master branche already, you can just pull the latest version, create a local.php config file (as described in the readme) and you're good to go!
