### ISSUE TITLE
warning when creating instance

### ISSUE THREAD

**Issue by TimVNL** [kbentlage/da-redis-management#11]
Hello,

I get the following warning when creating a redis instance 

Warning: shell_exec() has been disabled for security reasons in /usr/local/directadmin/plugins/redis_management/php/Controllers/RedisController.php on line 448 Warning: shell_exec() has been disabled for security reasons in /usr/local/directadmin/plugins/redis_management/php/Controllers/RedisController.php on line 448 

How can i fix this so the redis managment can us shell_exec?

Using PHP7.3 with the latest DirectAdmin

**Comment by mijnhost** [comment]
Try the following command:

```
cd /usr/local/directadmin/custombuild
./build set secure_php no
./build php n
```
