### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by Jouwhost** [kbentlage/da-redis-management#14]
When installing i get an error. I have 2 php versions and it seems to install fine on php7, it doesn't on php 5.6.
Not sure why because these kind of errors are new for me.

Warning: popen() has been disabled for security reasons in OS/Guess.php on line 241
PHP Warning:  popen() has been disabled for security reasons in /usr/local/php56/lib/php/OS/Guess.php on line 241

Warning: fgets() expects parameter 1 to be resource, null given in OS/Guess.php on line 242
PHP Warning:  fgets() expects parameter 1 to be resource, null given in /usr/local/php56/lib/php/OS/Guess.php on line 242

Warning: pclose() expects parameter 1 to be resource, null given in OS/Guess.php on line 251
PHP Warning:  pclose() expects parameter 1 to be resource, null given in /usr/local/php56/lib/php/OS/Guess.php on line 251
downloading redis-2.2.8.tgz ...
Starting to download redis-2.2.8.tgz (192,131 bytes)
.........................................done: 192,131 bytes
20 source files, building
running: phpize56

Warning: popen() has been disabled for security reasons in PEAR/Builder.php on line 465
PHP Warning:  popen() has been disabled for security reasons in /usr/local/php56/lib/php/PEAR/Builder.php on line 465
ERROR: failed to run `phpize56'

Do i need to install something or change configs? I hope you can give some advice.

**Comment by infernusec** [comment]
> When installing i get an error. I have 2 php versions and it seems to install fine on php7, it doesn't on php 5.6.
> Not sure why because these kind of errors are new for me.
> 
> Warning: popen() has been disabled for security reasons in OS/Guess.php on line 241
> PHP Warning: popen() has been disabled for security reasons in /usr/local/php56/lib/php/OS/Guess.php on line 241
> 
> Warning: fgets() expects parameter 1 to be resource, null given in OS/Guess.php on line 242
> PHP Warning: fgets() expects parameter 1 to be resource, null given in /usr/local/php56/lib/php/OS/Guess.php on line 242
> 
> Warning: pclose() expects parameter 1 to be resource, null given in OS/Guess.php on line 251
> PHP Warning: pclose() expects parameter 1 to be resource, null given in /usr/local/php56/lib/php/OS/Guess.php on line 251
> downloading redis-2.2.8.tgz ...
> Starting to download redis-2.2.8.tgz (192,131 bytes)
> .........................................done: 192,131 bytes
> 20 source files, building
> running: phpize56
> 
> Warning: popen() has been disabled for security reasons in PEAR/Builder.php on line 465
> PHP Warning: popen() has been disabled for security reasons in /usr/local/php56/lib/php/PEAR/Builder.php on line 465
> ERROR: failed to run `phpize56'
> 
> Do i need to install something or change configs? I hope you can give some advice.

your PHP configuration not set correctly...
you have to enable the function popen in php.ini file.

the default location is:
/usr/local/php56/lib/php.ini
/usr/local/php[YOUR_PHP_VERSION]/lib/php.ini
