### ISSUE TITLE
The plugin does not remove redis instance if user deleted from DA panel

### ISSUE THREAD

**Issue by bogdanshy** [kbentlage/da-redis-management#4]
The plugin does not remove redis instance if user deleted from DA panel.

Files left:
/etc/redis/instances/70XX.conf

and entrance in /usr/local/directadmin/plugins/redis_management/data/instances.json file.

**Comment by kbentlage** [comment]
Implemented auto cleanup functionality on user deletion in version 1.1.1

#6
